name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Coeur
        run: pip install blog-coeur

      - name: Build Blog
        run: blog-coeur ssg build

      - name: Deploy to output branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin
          git checkout -b output 
          git rm -rf .
          cp -r public/* .
          git add .
          git commit -m "Deploy to output branch" > /dev/null
          git push --force origin output