name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10.12]
        poetry-version: [1.8.3]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update __init__.py with version
        run: |
          echo "__version__ = '${{ github.event.release.tag_name }}'" > coeur/__init__.py
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
